mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name='polls'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/',views.detail, name='detail'),
    path('<int:question_id>/results',views.results, name='results'),
    path('<int:question_id>/vote',views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    ques_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.ques_text

    def was_pub_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse

# Create your views here.

def index(request):
  latest_question_list = Question.objects.order_by('-pub_date')[:5]
  context = {'latest_question_list': latest_question_list}
  return render(request, 'polls/index.html', context)

def detail(request, question_id):
  try:
    question=Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'polls/detail.html', {'question':question})

def results(request, question_id):
  question=get_object_or_404(Question, pk=question_id)
  return render(request, 'polls/results.html', {'question':question})

def vote(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  try:
      selected_choice = question.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
      return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice.",})
  else:
      selected_choice.votes += 1
      selected_choice.save()
      return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% extends 'polls/main.html' %} {% block content %}
<h1>Poll Detail</h1>
<h2>{{ question.ques_text }}</h2>
{% if error_message %}
<p><strong>{{ error_message }} </strog></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="POST">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>
{% endblock %} </strong></p>

polls/templates/polls/index.html
{% extends 'polls/main.html' %}
{% block content %}
<h1>Latest Polls Questions</h1>
        {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                    <li><a href="{% url 'polls:detail' question.id %}">{{ question.ques_text }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
{% endblock %}

polls/templates/polls/main.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <link rel="stylesheet" href="" />
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

polls/templates/polls/results.html
{% extends 'polls/main.html' %} {% block content %}
<h1>{{ question.ques_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} : {{ choice.votes }} vote</li>
  {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}